In [1]:
import pandas as pd

In [22]:
df = pd.read_excel("Itens - 2026-09-17T133257.920.xlsx")

In [3]:
df

,Empresa,Nº Contrato,Id Resp.Financeiro,Descrição Resp.Financeiro,Situação Parceiro,CPF Titular,Vigência Início Contrato,Vigência Fim Contrato,Data Protocolo,Data Venda,...,Usuário Integração,Data Modificação Bitix,Qt. Vidas Empresa,Valor do Custo,Valor da Taxa,Código postal,Estado Civil Beneficiário,Grupo de Materiais,Tipo Contrato,Tipo Movimentação
0,1000,1,35.0,SINDESTIVA,NaN,000.287.437-76,2019-11-20,2024-04-14 00:00:00,2019-11-22 00:00:00,2019-11-20 00:00:00,...,DSANTOS,NaT,VIDA CANCELADA,760.35,0.0,29010710,Solteiro,E,YCES,MOVIMENTAÇÃO
1,1000,1,6940.0,ANTONIO SERGIO NASCIMENTO DOS SANTOS,NaN,000.287.437-76,2019-11-20,2024-04-14 00:00:00,2019-11-22 00:00:00,2019-11-20 00:00:00,...,DSANTOS,NaT,VIDA CANCELADA,760.35,0.0,29010710,Solteiro,E,YCES,MOVIMENTAÇÃO
2,1000,1,35.0,SINDESTIVA,NaN,000.724.097-03,2019-11-20,2024-04-14 00:00:00,2019-11-22 00:00:00,2019-11-20 00:00:00,...,DSANTOS,NaT,VIDA CANCELADA,1041.69,0.0,29010710,Solteiro,E,YCES,MOVIMENTAÇÃO
3,1000,1,6942.0,ANTONIO DOS SANTOS BARROS,NaN,000.724.097-03,2019-11-20,2024-04-14 00:00:00,2019-11-22 00:00:00,2019-11-20 00:00:00,...,DSANTOS,NaT,VIDA CANCELADA,567.42,0.0,29010710,Solteiro,E,YCES,MOVIMENTAÇÃO
4,1000,1,6942.0,ANTONIO DOS SANTOS BARROS,NaN,000.724.097-03,2019-11-20,2024-04-14 00:00:00,2019-11-22 00:00:00,2019-11-20 00:00:00,...,DSANTOS,NaT,VIDA CANCELADA,174.60,0.0,29010710,Solteiro,E,YCES,MOVIMENTAÇÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175217,1000,32395,172849.0,FERRARI HOTEIS E EVENTOS LTDA,NaN,073.559.367-19,2026-09-26,9999-12-31 00:00:00,2026-09-15 00:00:00,2026-09-15 00:00:00,...,USER_INTEGR,2026-09-16,VIDA CANCELADA,0.00,0.0,29230000,Solteiro,E,YCEM,VIDA NOVA
175218,1000,32396,172856.0,SERRA EXTINTORES LTDA,NaN,101.531.977-73,2026-10-01,9999-12-31 00:00:00,2026-09-15 00:00:00,2026-09-15 00:00:00,...,USER_INTEGR,2026-09-15,VIDA CANCELADA,0.00,0.0,29171415,Casado,GM,YCEM,VIDA NOVA
175219,1000,32396,172856.0,SERRA EXTINTORES LTDA,NaN,101.531.977-73,2026-10-01,9999-12-31 00:00:00,2026-09-15 00:00:00,2026-09-15 00:00:00,...,USER_INTEGR,2026-09-15,VIDA CANCELADA,0.00,0.0,29171415,Casado,GM,YCEM,VIDA NOVA
175220,1000,32397,172865.0,VIXSHOPPING COMERCIO ONLINE LTDA,NaN,145.403.057-78,2026-10-01,9999-12-31 00:00:00,2026-09-11 00:00:00,2026-09-11 00:00:00,...,USER_INTEGR,2026-09-15,VIDA CANCELADA,0.00,0.0,29164830,Solteiro,N,YCEM,VIDA NOVA
175221,1000,32397,172865.0,VIXSHOPPING COMERCIO ONLINE LTDA,NaN,191.889.817-03,2026-10-01,9999-12-31 00:00:00,2026-09-11 00:00:00,2026-09-11 00:00:00,...,USER_INTEGR,2026-09-15,VIDA CANCELADA,0.00,0.0,29164830,Solteiro,N,YCEM,VIDA NOVA

In [23]:
carteira_exec = pd.read_excel("2026.09 - atualizado em 15.09.xlsx")

In [24]:
df = pd.merge(df, carteira_exec, how = 'left', right_on = 'ID Parceiro', left_on = 'Id Corretora')
df = df[df['Tipo Movimentação'] == 'VIDA NOVA']

In [25]:
df

,Empresa,Nº Contrato,Id Resp.Financeiro,Descrição Resp.Financeiro,Situação Parceiro,CPF Titular,Vigência Início Contrato,Vigência Fim Contrato,Data Protocolo,Data Venda,...,Código postal,Estado Civil Beneficiário,Grupo de Materiais,Tipo Contrato,Tipo Movimentação,ID Parceiro,Nome Parceiro,Nome Analista,ID Analist,NOME
89,1000,1,7020.0,PAULO DOUGLAS ALVES PINHEIRO,NaN,022.744.147-85,2019-11-20,2024-04-14 00:00:00,2019-11-22 00:00:00,2019-11-20 00:00:00,...,29010710,Casado,E,YCES,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA
965,1000,1,7882.0,ROGERIO PINTO DE OLIVEIRA,NaN,820.875.207-04,2019-11-20,2024-04-14 00:00:00,2019-11-22 00:00:00,2019-11-20 00:00:00,...,29010710,Solteiro,E,YCES,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA
966,1000,1,7882.0,ROGERIO PINTO DE OLIVEIRA,NaN,820.875.207-04,2019-11-20,2024-04-14 00:00:00,2019-11-22 00:00:00,2019-11-20 00:00:00,...,29010710,Casado,E,YCES,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA
1001,1000,1,7914.0,CARLOS ALBERTO MESSIAS,NaN,845.232.807-97,2019-11-20,2024-04-14 00:00:00,2019-11-22 00:00:00,2019-11-20 00:00:00,...,29010710,Solteiro,E,YCES,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA
1651,1000,2,8591.0,INGRID SOARES DA SILVA,NaN,081.468.487-45,2002-10-10,2024-01-31 00:00:00,2002-10-10 00:00:00,2002-10-10 00:00:00,...,29025675,Casado,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175245,1000,32395,172849.0,FERRARI HOTEIS E EVENTOS LTDA,NaN,073.559.367-19,2026-09-26,9999-12-31 00:00:00,2026-09-15 00:00:00,2026-09-15 00:00:00,...,29230000,Solteiro,E,YCEM,VIDA NOVA,134055.0,SALUS CORRETORA LTDA,THAIS PEREIRA SILVA,115335.0,THAIS
175246,1000,32396,172856.0,SERRA EXTINTORES LTDA,NaN,101.531.977-73,2026-10-01,9999-12-31 00:00:00,2026-09-15 00:00:00,2026-09-15 00:00:00,...,29171415,Casado,GM,YCEM,VIDA NOVA,6862.0,JOY CORRETORA DE PLANOS DE SAUDE E SEGUR,TAIS FRIZERA QUEIROZ,159908.0,TAIS
175247,1000,32396,172856.0,SERRA EXTINTORES LTDA,NaN,101.531.977-73,2026-10-01,9999-12-31 00:00:00,2026-09-15 00:00:00,2026-09-15 00:00:00,...,29171415,Casado,GM,YCEM,VIDA NOVA,6862.0,JOY CORRETORA DE PLANOS DE SAUDE E SEGUR,TAIS FRIZERA QUEIROZ,159908.0,TAIS
175248,1000,32397,172865.0,VIXSHOPPING COMERCIO ONLINE LTDA,NaN,145.403.057-78,2026-10-01,9999-12-31 00:00:00,2026-09-11 00:00:00,2026-09-11 00:00:00,...,29164830,Solteiro,N,YCEM,VIDA NOVA,6861.0,MASTER CORRETORA,ELEN BRITO VARGAS,74019.0,ELEN
175249,1000,32397,172865.0,VIXSHOPPING COMERCIO ONLINE LTDA,NaN,191.889.817-03,2026-10-01,9999-12-31 00:00:00,2026-09-11 00:00:00,2026-09-11 00:00:00,...,29164830,Solteiro,N,YCEM,VIDA NOVA,6861.0,MASTER CORRETORA,ELEN BRITO VARGAS,74019.0,ELEN

In [26]:
df['Data Início Beneficiário'] = pd.to_datetime(df['Data Início Beneficiário'], errors='coerce',dayfirst=True)
df['Data Inclusão Vida'] = pd.to_datetime(df['Data Inclusão Vida'], errors='coerce',dayfirst=True)
df['Diferenca'] = (df['Data Inclusão Vida'] - df['Data Início Beneficiário']).dt.days

In [27]:
Status_Beneficiario = 'Ativado'
Status_Contrato = "Aprovado"
Status_Vida = ['Ag.Ativação','Aposentado / Demitido','Ativo','Em Análise']
df = df[(df['Descrição Status Atual Beneficiário'] == Status_Beneficiario) & (df['Descrição Status Atual Contrato'] == Status_Contrato) & (df['Descrição Status Vida'].isin(Status_Vida))]

In [28]:
df_nao_corretos = df[df['Diferenca'] > 0]
df_nao_corretos = df_nao_corretos[df_nao_corretos['Descrição Status Atual Beneficiário'] == 'Ativado']
df_nao_corretoss = df_nao_corretos[['Descrição Beneficiário', 'Data Início Beneficiário', 'Data Inclusão Vida', 'Diferenca']]
df_nao_corretoss

Empty DataFrame
Columns: [Descrição Beneficiário, Data Início Beneficiário, Data Inclusão Vida, Diferenca]
Index: []

In [29]:
df_certo = df[df['Diferenca'] <= 0]
df_certo

,Empresa,Nº Contrato,Id Resp.Financeiro,Descrição Resp.Financeiro,Situação Parceiro,CPF Titular,Vigência Início Contrato,Vigência Fim Contrato,Data Protocolo,Data Venda,...,Estado Civil Beneficiário,Grupo de Materiais,Tipo Contrato,Tipo Movimentação,ID Parceiro,Nome Parceiro,Nome Analista,ID Analist,NOME,Diferenca
1652,1000,3,8592.0,FABIOLA SUAREZ GONZALEZ,NaN,811.328.917-87,2005-02-10,9999-12-31 00:00:00,2005-02-10 00:00:00,2005-02-10 00:00:00,...,Casado,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0
1653,1000,4,8593.0,LUZIMARA CROCE,NaN,969.074.957-91,2005-06-10,9999-12-31 00:00:00,2005-06-10 00:00:00,2005-06-10 00:00:00,...,Solteiro,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0
1655,1000,6,8595.0,CLECIA JOANA DE BORTOLI,NaN,051.884.427-79,2005-08-10,9999-12-31 00:00:00,2005-08-10 00:00:00,2005-08-10 00:00:00,...,Solteiro,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0
1656,1000,7,8596.0,OLAVIO NATAL DE BORTOLI,NaN,249.718.207-87,2005-08-10,9999-12-31 00:00:00,2005-08-10 00:00:00,2005-08-10 00:00:00,...,Casado,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0
1658,1000,8,8598.0,CLEVERSON OLAVO DE BORTOLI,NaN,009.872.837-74,2005-08-10,9999-12-31 00:00:00,2005-08-10 00:00:00,2005-08-10 00:00:00,...,Casado,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175218,1000,32375,172740.0,PADARIA E CONFEITARIA DA ANA LTDA,NaN,055.768.637-71,2026-09-21,9999-12-31 00:00:00,2026-09-14 00:00:00,2026-09-14 00:00:00,...,Solteiro,E,YCEM,VIDA NOVA,6847.0,UNIPLAN CORRETORA,TAIS FRIZERA QUEIROZ,159908.0,TAIS,-7.0
175219,1000,32375,172740.0,PADARIA E CONFEITARIA DA ANA LTDA,NaN,096.682.497-04,2026-09-21,9999-12-31 00:00:00,2026-09-14 00:00:00,2026-09-14 00:00:00,...,Solteiro,E,YCEM,VIDA NOVA,6847.0,UNIPLAN CORRETORA,TAIS FRIZERA QUEIROZ,159908.0,TAIS,-7.0
175222,1000,32377,172751.0,37.934.779 KARINY LAURINDO ARGOLO BANDEI,NaN,135.164.077-19,2026-09-25,9999-12-31 00:00:00,2026-09-14 00:00:00,2026-09-14 00:00:00,...,Solteiro,E,YCEM,VIDA NOVA,134055.0,SALUS CORRETORA LTDA,THAIS PEREIRA SILVA,115335.0,THAIS,-11.0
175223,1000,32377,172751.0,37.934.779 KARINY LAURINDO ARGOLO BANDEI,NaN,135.164.077-19,2026-09-25,9999-12-31 00:00:00,2026-09-14 00:00:00,2026-09-14 00:00:00,...,Solteiro,E,YCEM,VIDA NOVA,134055.0,SALUS CORRETORA LTDA,THAIS PEREIRA SILVA,115335.0,THAIS,-11.0
175224,1000,32377,172751.0,37.934.779 KARINY LAURINDO ARGOLO BANDEI,NaN,135.164.077-19,2026-09-25,9999-12-31 00:00:00,2026-09-14 00:00:00,2026-09-14 00:00:00,...,Solteiro,E,YCEM,VIDA NOVA,134055.0,SALUS CORRETORA LTDA,THAIS PEREIRA SILVA,115335.0,THAIS,-11.0

In [30]:
df_certo['Data Inclusão Vida'] = pd.to_datetime(
    df_certo['Data Inclusão Vida'],
    dayfirst=True,
    errors='coerce'
)

df_certo['Competencia'] = df_certo['Data Inclusão Vida'].dt.strftime('%m/%Y')

df_certo['Data Inclusão Vida'] = df_certo['Data Inclusão Vida'].dt.strftime('%d/%m/%Y')

C:\Users\mario.lira\AppData\Local\Temp\ipykernel_20488\108588159.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_certo['Data Inclusão Vida'] = pd.to_datetime(
C:\Users\mario.lira\AppData\Local\Temp\ipykernel_20488\108588159.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_certo['Competencia'] = df_certo['Data Inclusão Vida'].dt.strftime('%m/%Y')
C:\Users\mario.lira\AppData\Local\Temp\ipykernel_20488\108588159.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_certo['Data Inclusão Vida'] = df_certo['Data Inclusão Vida'].dt.strftime('%d/%m/%Y')

In [31]:
df_certo

,Empresa,Nº Contrato,Id Resp.Financeiro,Descrição Resp.Financeiro,Situação Parceiro,CPF Titular,Vigência Início Contrato,Vigência Fim Contrato,Data Protocolo,Data Venda,...,Grupo de Materiais,Tipo Contrato,Tipo Movimentação,ID Parceiro,Nome Parceiro,Nome Analista,ID Analist,NOME,Diferenca,Competencia
1652,1000,3,8592.0,FABIOLA SUAREZ GONZALEZ,NaN,811.328.917-87,2005-02-10,9999-12-31 00:00:00,2005-02-10 00:00:00,2005-02-10 00:00:00,...,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0,02/2005
1653,1000,4,8593.0,LUZIMARA CROCE,NaN,969.074.957-91,2005-06-10,9999-12-31 00:00:00,2005-06-10 00:00:00,2005-06-10 00:00:00,...,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0,06/2005
1655,1000,6,8595.0,CLECIA JOANA DE BORTOLI,NaN,051.884.427-79,2005-08-10,9999-12-31 00:00:00,2005-08-10 00:00:00,2005-08-10 00:00:00,...,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0,08/2005
1656,1000,7,8596.0,OLAVIO NATAL DE BORTOLI,NaN,249.718.207-87,2005-08-10,9999-12-31 00:00:00,2005-08-10 00:00:00,2005-08-10 00:00:00,...,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0,08/2005
1658,1000,8,8598.0,CLEVERSON OLAVO DE BORTOLI,NaN,009.872.837-74,2005-08-10,9999-12-31 00:00:00,2005-08-10 00:00:00,2005-08-10 00:00:00,...,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0,08/2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175218,1000,32375,172740.0,PADARIA E CONFEITARIA DA ANA LTDA,NaN,055.768.637-71,2026-09-21,9999-12-31 00:00:00,2026-09-14 00:00:00,2026-09-14 00:00:00,...,E,YCEM,VIDA NOVA,6847.0,UNIPLAN CORRETORA,TAIS FRIZERA QUEIROZ,159908.0,TAIS,-7.0,09/2026
175219,1000,32375,172740.0,PADARIA E CONFEITARIA DA ANA LTDA,NaN,096.682.497-04,2026-09-21,9999-12-31 00:00:00,2026-09-14 00:00:00,2026-09-14 00:00:00,...,E,YCEM,VIDA NOVA,6847.0,UNIPLAN CORRETORA,TAIS FRIZERA QUEIROZ,159908.0,TAIS,-7.0,09/2026
175222,1000,32377,172751.0,37.934.779 KARINY LAURINDO ARGOLO BANDEI,NaN,135.164.077-19,2026-09-25,9999-12-31 00:00:00,2026-09-14 00:00:00,2026-09-14 00:00:00,...,E,YCEM,VIDA NOVA,134055.0,SALUS CORRETORA LTDA,THAIS PEREIRA SILVA,115335.0,THAIS,-11.0,09/2026
175223,1000,32377,172751.0,37.934.779 KARINY LAURINDO ARGOLO BANDEI,NaN,135.164.077-19,2026-09-25,9999-12-31 00:00:00,2026-09-14 00:00:00,2026-09-14 00:00:00,...,E,YCEM,VIDA NOVA,134055.0,SALUS CORRETORA LTDA,THAIS PEREIRA SILVA,115335.0,THAIS,-11.0,09/2026
175224,1000,32377,172751.0,37.934.779 KARINY LAURINDO ARGOLO BANDEI,NaN,135.164.077-19,2026-09-25,9999-12-31 00:00:00,2026-09-14 00:00:00,2026-09-14 00:00:00,...,E,YCEM,VIDA NOVA,134055.0,SALUS CORRETORA LTDA,THAIS PEREIRA SILVA,115335.0,THAIS,-11.0,09/2026

In [32]:
ACOM = ['ODO','SEM']

df_saude = df_certo[~df_certo['Id Acomodação'].isin(ACOM)]

In [33]:
ACOM = ['ODO']
df_odonto = df_certo[df_certo['Id Acomodação'].isin(ACOM)]

In [34]:
df_saude

,Empresa,Nº Contrato,Id Resp.Financeiro,Descrição Resp.Financeiro,Situação Parceiro,CPF Titular,Vigência Início Contrato,Vigência Fim Contrato,Data Protocolo,Data Venda,...,Grupo de Materiais,Tipo Contrato,Tipo Movimentação,ID Parceiro,Nome Parceiro,Nome Analista,ID Analist,NOME,Diferenca,Competencia
1652,1000,3,8592.0,FABIOLA SUAREZ GONZALEZ,NaN,811.328.917-87,2005-02-10,9999-12-31 00:00:00,2005-02-10 00:00:00,2005-02-10 00:00:00,...,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0,02/2005
1653,1000,4,8593.0,LUZIMARA CROCE,NaN,969.074.957-91,2005-06-10,9999-12-31 00:00:00,2005-06-10 00:00:00,2005-06-10 00:00:00,...,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0,06/2005
1655,1000,6,8595.0,CLECIA JOANA DE BORTOLI,NaN,051.884.427-79,2005-08-10,9999-12-31 00:00:00,2005-08-10 00:00:00,2005-08-10 00:00:00,...,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0,08/2005
1656,1000,7,8596.0,OLAVIO NATAL DE BORTOLI,NaN,249.718.207-87,2005-08-10,9999-12-31 00:00:00,2005-08-10 00:00:00,2005-08-10 00:00:00,...,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0,08/2005
1658,1000,8,8598.0,CLEVERSON OLAVO DE BORTOLI,NaN,009.872.837-74,2005-08-10,9999-12-31 00:00:00,2005-08-10 00:00:00,2005-08-10 00:00:00,...,GM,YCCA,VIDA NOVA,601.0,"ILHA AZUL SAUDE, SEGUROS, PREVIDENCIA, A",MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,0.0,08/2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175210,1000,32372,172729.0,AGIL PARTICIPACOES E INVESTIMENTOS LTDA,NaN,027.460.486-80,2026-10-01,9999-12-31 00:00:00,2026-09-10 00:00:00,2026-09-10 00:00:00,...,N,YCEM,VIDA NOVA,3562.0,EXPANSAO CORRETORA DE BENEFICIOS E SEGUR,MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,-21.0,09/2026
175211,1000,32372,172729.0,AGIL PARTICIPACOES E INVESTIMENTOS LTDA,NaN,027.460.486-80,2026-10-01,9999-12-31 00:00:00,2026-09-10 00:00:00,2026-09-10 00:00:00,...,N,YCEM,VIDA NOVA,3562.0,EXPANSAO CORRETORA DE BENEFICIOS E SEGUR,MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,-21.0,09/2026
175212,1000,32372,172729.0,AGIL PARTICIPACOES E INVESTIMENTOS LTDA,NaN,027.460.486-80,2026-10-01,9999-12-31 00:00:00,2026-09-10 00:00:00,2026-09-10 00:00:00,...,N,YCEM,VIDA NOVA,3562.0,EXPANSAO CORRETORA DE BENEFICIOS E SEGUR,MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,-21.0,09/2026
175213,1000,32372,172729.0,AGIL PARTICIPACOES E INVESTIMENTOS LTDA,NaN,027.460.486-80,2026-10-01,9999-12-31 00:00:00,2026-09-10 00:00:00,2026-09-10 00:00:00,...,N,YCEM,VIDA NOVA,3562.0,EXPANSAO CORRETORA DE BENEFICIOS E SEGUR,MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,-21.0,09/2026
175214,1000,32372,172729.0,AGIL PARTICIPACOES E INVESTIMENTOS LTDA,NaN,027.460.486-80,2026-10-01,9999-12-31 00:00:00,2026-09-10 00:00:00,2026-09-10 00:00:00,...,N,YCEM,VIDA NOVA,3562.0,EXPANSAO CORRETORA DE BENEFICIOS E SEGUR,MARIA CLARA RIBEIRO BOREL,148624.0,MARIA,-21.0,09/2026

In [44]:
df_saude_agru_comp_analista = df_saude.groupby(['Competencia', 'NOME']).agg({'Id Corretora': 'count'}).reset_index()
df_saude_agru_comp_analista['Competencia'] = pd.to_datetime(df_saude_agru_comp_analista['Competencia'], format='%m/%Y', errors='coerce')
df_saude_agru_comp_analista=df_saude_agru_comp_analista[df_saude_agru_comp_analista['Competencia']>pd.to_datetime('2025-12-01')]
df_saude_agru_comp_analista

    Competencia        NOME  Id Corretora
29   2026-01-01        ELEN           147
30   2026-01-01       JULIA            10
31   2026-01-01       MARIA           124
32   2026-01-01        TAIS            93
33   2026-01-01       THAIS           190
65   2026-02-01        ELEN            57
66   2026-02-01       JULIA             6
67   2026-02-01       MARIA            61
68   2026-02-01        TAIS           119
69   2026-02-01       THAIS           146
102  2026-03-01        ELEN           154
103  2026-03-01       JULIA            13
104  2026-03-01       MARIA           205
105  2026-03-01      OUTROS             3
106  2026-03-01        TAIS           227
107  2026-03-01       THAIS           263
143  2026-04-01        ELEN            88
144  2026-04-01       JULIA             9
145  2026-04-01       MARIA           139
146  2026-04-01        TAIS           174
147  2026-04-01       THAIS           194
180  2026-05-01        ELEN           144
181  2026-05-01       JULIA             8
182  2026-05-01       MARIA           208
183  2026-05-01        TAIS           119
184  2026-05-01       THAIS           189
219  2026-06-01        ELEN           168
220  2026-06-01       JULIA             3
221  2026-06-01       MARIA           115
222  2026-06-01  MEDIATORIE             3
223  2026-06-01      OUTROS             6
224  2026-06-01        TAIS           117
225  2026-06-01       THAIS           198
258  2026-07-01        ELEN           138
259  2026-07-01       JULIA             6
260  2026-07-01       MARIA           102
261  2026-07-01  MEDIATORIE            19
262  2026-07-01        TAIS           140
263  2026-07-01       THAIS           192
300  2026-08-01        ELEN           261
301  2026-08-01       JULIA            10
302  2026-08-01       MARIA           104
303  2026-08-01  MEDIATORIE            61
304  2026-08-01      OUTROS             6
305  2026-08-01        TAIS           163
306  2026-08-01       THAIS           232
345  2026-09-01        ELEN            25
346  2026-09-01       JULIA             4
347  2026-09-01       MARIA            32
348  2026-09-01  MEDIATORIE            18
349  2026-09-01        TAIS            47
350  2026-09-01       THAIS            78

In [45]:
df_odonto_agru_comp_analista = df_odonto.groupby(['Competencia', 'NOME']).agg({'Id Corretora': 'count'}).reset_index()
df_odonto_agru_comp_analista['Competencia'] = pd.to_datetime(df_odonto_agru_comp_analista['Competencia'], format='%m/%Y', errors='coerce')
df_odonto_agru_comp_analista=df_odonto_agru_comp_analista[df_odonto_agru_comp_analista['Competencia']>pd.to_datetime('2025-12-01')]
df_odonto_agru_comp_analista

    Competencia        NOME  Id Corretora
19   2026-01-01        ELEN           108
20   2026-01-01       JULIA            26
21   2026-01-01       MARIA            43
22   2026-01-01        TAIS            39
23   2026-01-01       THAIS            70
42   2026-02-01        ELEN            48
43   2026-02-01       JULIA            14
44   2026-02-01       MARIA            30
45   2026-02-01        TAIS           168
46   2026-02-01       THAIS            54
66   2026-03-01        ELEN            85
67   2026-03-01       JULIA            15
68   2026-03-01       MARIA           115
69   2026-03-01        TAIS           149
70   2026-03-01       THAIS           151
89   2026-04-01        ELEN            57
90   2026-04-01       JULIA            13
91   2026-04-01       MARIA           158
92   2026-04-01        TAIS            84
93   2026-04-01       THAIS           120
111  2026-05-01        ELEN           118
112  2026-05-01       JULIA            36
113  2026-05-01       MARIA           152
114  2026-05-01        TAIS           126
115  2026-05-01       THAIS           128
136  2026-06-01        ELEN           124
137  2026-06-01       JULIA             9
138  2026-06-01       MARIA           166
139  2026-06-01  MEDIATORIE            10
140  2026-06-01        TAIS           115
141  2026-06-01       THAIS            57
160  2026-07-01        ELEN            66
161  2026-07-01       JULIA            10
162  2026-07-01       MARIA            87
163  2026-07-01  MEDIATORIE            45
164  2026-07-01        TAIS           173
165  2026-07-01       THAIS           137
186  2026-08-01        ELEN           195
187  2026-08-01       JULIA             3
188  2026-08-01       MARIA            52
189  2026-08-01  MEDIATORIE            42
190  2026-08-01        TAIS           180
191  2026-08-01       THAIS            77
211  2026-09-01        ELEN            46
212  2026-09-01       MARIA            13
213  2026-09-01  MEDIATORIE            25
214  2026-09-01        TAIS            70
215  2026-09-01       THAIS            23

In [35]:
df_saude_group = df_saude.groupby('Competencia').agg({'Descrição Beneficiário': 'count'}).reset_index()

In [ ]:

df_saude_group['Competencia'] = pd.to_datetime(df_saude_group['Competencia'], format='%m/%Y', errors='coerce')
df_saude_group=df_saude_group[df_saude_group['Competencia']>pd.to_datetime('2025-12-01')]
df_saude_group

    Competencia  Descrição Beneficiário
10   2026-01-01                     564
21   2026-02-01                     391
33   2026-03-01                     865
45   2026-04-01                     604
55   2026-05-01                     668
67   2026-06-01                     610
80   2026-07-01                     597
94   2026-08-01                     837
110  2026-09-01                     204

In [37]:
df_odonto_group = df_odonto.groupby('Competencia').agg({'Descrição Beneficiário': 'count'}).reset_index()

df_odonto_group['Competencia'] = pd.to_datetime(df_odonto_group['Competencia'], format='%m/%Y', errors='coerce')
df_odonto_group=df_odonto_group[df_odonto_group['Competencia']>pd.to_datetime('2025-12-01')]
df_odonto_group

   Competencia  Descrição Beneficiário
4   2026-01-01                     286
9   2026-02-01                     314
14  2026-03-01                     515
19  2026-04-01                     432
24  2026-05-01                     560
29  2026-06-01                     481
34  2026-07-01                     518
39  2026-08-01                     549
44  2026-09-01                     177